config/routes.rb
Rails.application.routes.draw do
  root 'url_shorten#index'
  get '/:small_url' => 'url_shorten#show'
  post '/create' => 'url_shorten#create', as: 'shortner'
  patch '/create' => 'url_shorten#create'

end

app/models/url_shorten.rb
class UrlShorten < ActiveRecord::Base
  validates :small_url, uniqueness: true

  def url
    new_url = SecureRandom.hex(2)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/url_shorten_controller.rb
class UrlShortenController < ApplicationController
  before_action :clean_params, only: [:create]

  def index
    @new_url = UrlShorten.new

  end

  def show
    @url_found = UrlShorten.find_by(small_url: params[:small_url])

    if @url_found
      if @url_found.original_url.include? "http"
        redirect_to @url_found.original_url
      else
        @url_found = @url_found.original_url
        @url_found.prepend("http://")
        redirect_to @url_found
      end
    else
      redirect_to root_path
    end

  end

  def create
    @new_url = UrlShorten.new(clean_params)
    @new_url.save
    @user_last_url = UrlShorten.last
    # redirect_to create_path
  end


  private
    def clean_params
      #require for table name permit that value from form (table column)
      params.require(:url_shorten).permit(:original_url, :small_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/url_shorten_helper.rb
module UrlShortenHelper
end

app/helpers/url_shortner_helper.rb
module UrlShortnerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/url_shorten/_url.html.erb
<div class="jumbotron center-block">
  <h3>Your Beautiful New Url:</h3>
  <p>
    <a href="<%= @user_last_url.small_url %>" target="_blank"> 
      <%= root_url %><%= @user_last_url.small_url %></a>
  </p>

</div>

app/views/url_shorten/create.html.erb
<div class="container center-block">

  <h1>Shorten your URL!</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <p>Paste in your long URL and we will give you a short one you can use! </p>
    </div>
  </div>

  <div class="row center-block">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@new_url, url: shortner_path) do |f|%>
        <div class="form-group">
          <%= f.hidden_field :small_url, :value => UrlShorten.new.url %>
          <%= f.text_field (:original_url), class: "form-control" %>
        </div>
        <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
        Shorten your URL!
        <% end %>
      <% end %>
    </div>
  </div>

  <% if @user_last_url %>
    <%= flash[:notice] = render 'url' %>
  <%end%>

</div>

app/views/url_shorten/index.html.erb
<div class="container center-block">

  <h1>Shorten your URL!</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <p>Paste in your long URL and we will give you a short one you can use! </p>
    </div>
  </div>

  <div class="row center-block">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@new_url, url: shortner_path) do |f|%>
        <div class="form-group">
          <%= f.hidden_field :small_url, :value => UrlShorten.new.url %>
          <%= f.text_field (:original_url), class: "form-control" %>
        </div>
        <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
        Shorten your URL!
        <% end %>
      <% end %>
    </div>
  </div>
  
</div>

app/views/url_shorten/show.html.erb
<%= @url_found %>